In [1]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32_450, 0.66, 8014)
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'), ('ESP', 'XDA205856')]

In [2]:
for passport in sorted(traveler_ids):
    print('%s/%s' % passport)

BRA/CE342567
ESP/XDA205856
USA/31195855


In [3]:
for country, _ in traveler_ids:
    print(country)

USA
BRA
ESP


In [4]:
a, b, *c = range(10)
a, b, c

(0, 1, [2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a, b, *c, a, b = range(10)

In [6]:
a, b, c

(8, 9, [2, 3, 4, 5, 6, 7])

In [10]:
def fun(a, b, c, d, *rest):
    return a, b, c, d, rest

fun(*[1, 2], 3, *range(5))

(1, 2, 3, 0, (1, 2, 3, 4))

In [8]:
*range(4), 4

(0, 1, 2, 3, 4)

In [12]:
metro_areas = [
('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
('São Paulo', 'BR', 19.649, (-23.547778, -46.635833)),
]

In [15]:
for name, _, _, (lat, con) in metro_areas:
    print(name, lat, con)

Tokyo 35.689722 139.691667
Delhi NCR 28.613889 77.208889
Mexico City 19.433333 -99.133333
New York-Newark 40.808611 -74.020386
São Paulo -23.547778 -46.635833


In [21]:
for record in metro_areas:
    match record:
        case [str(name), *extra, (float(lat), float(lon)) as coord] if lon <= 0:
            print(name, lat, lon, extra, coord)

Mexico City 19.433333 -99.133333 ['MX', 20.142] (19.433333, -99.133333)
New York-Newark 40.808611 -74.020386 ['US', 20.104] (40.808611, -74.020386)
São Paulo -23.547778 -46.635833 ['BR', 19.649] (-23.547778, -46.635833)


In [ ]:
def handle_command(self, message):
    match message:
        case ['BEEPER', frequency, times]:
            ...
        case ['NECK', angle]:
            ...
        case ['LED', ident, intensity]:
            ...
        case _:
            raise InvalidCommand(message)

In [1]:
s = 'bicycle'
s[::3]

'bye'

In [22]:
l = [1, 2, 3]
id(l)

1497396677568

In [23]:
l *= 2
id(l)

1497396677568

In [24]:
l

[1, 2, 3, 1, 2, 3]

In [25]:
t = (1, 2, 3)
id(t)

1497396685376

In [26]:
t *= 2
t, id(t)

((1, 2, 3, 1, 2, 3), 1497395668704)

In [28]:
t = (1, 2, [30, 40])
t[2] += [50, 60]

TypeError: 'tuple' object does not support item assignment

In [29]:
t

(1, 2, [30, 40, 50, 60])

In [30]:
import dis
dis.dis('s[a] += b')

  0           0 RESUME                   0

  1           2 LOAD_NAME                0 (s)
              4 LOAD_NAME                1 (a)
              6 COPY                     2
              8 COPY                     2
             10 BINARY_SUBSCR
             14 LOAD_NAME                2 (b)
             16 BINARY_OP               13 (+=)
             20 SWAP                     3
             22 SWAP                     2
             24 STORE_SUBSCR
             28 RETURN_CONST             0 (None)


In [31]:
a = [3, 4, 1, 2, 5]
b = (3, 4, 1, 2, 5)

In [37]:
list.sort(a, reverse=True)

In [41]:
a.sort()

In [42]:
a

[1, 2, 3, 4, 5]

In [39]:
# list.sort(b)
sorted(b)

[1, 2, 3, 4, 5]

In [40]:
b

(3, 4, 1, 2, 5)

In [43]:
from array import array
from random import random

floats = array('d', (random() for i in range(10 ** 7)))
floats[-1]

0.40219405730960134

In [44]:
with open('floats.bin', 'wb') as fp:
    floats.tofile(fp)

In [46]:
floats2 = array('d')
with open('floats.bin', 'rb') as fp:
    floats2.fromfile(fp, 10**7)
floats2[-1]

0.40219405730960134

In [47]:
floats2 == floats

True

In [51]:
a= sorted(floats)
a[0], a[-1]

(1.1120404308506693e-07, 0.9999999798090575)

In [61]:
from array import array

octets = array('B', range(6))
m1 = memoryview(octets)

In [62]:
m1.tolist()

[0, 1, 2, 3, 4, 5]

In [66]:
m1

In [67]:
m2 = m1.cast('B', [2, 3])
m2.tolist()

[[0, 1, 2], [3, 4, 5]]

In [68]:
m3 = m1.cast('B', [3, 2])
m3.tolist()

[[0, 1], [2, 3], [4, 5]]

In [69]:
m2[1, 1] = 22
m3[1, 1] = 33
m1.tolist()

[0, 1, 2, 33, 22, 5]

In [70]:
numbers = array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)

5

In [71]:
memv

In [72]:
memv[0]

-2

In [73]:
memv_oct = memv.cast('B')
memv.tolist()

[-2, -1, 0, 1, 2]

In [74]:
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [75]:
memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

In [76]:
memv_oct.tolist()

[254, 255, 255, 255, 0, 4, 1, 0, 2, 0]

In [78]:
import numpy as np

a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [79]:
type(a)

numpy.ndarray

In [80]:
a.shape

(12,)

In [81]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [82]:
a[2]

array([ 8,  9, 10, 11])

In [83]:
a[2, 1]

9

In [84]:
a[(2, 1)]

9

In [85]:
a[:, 1]

array([1, 5, 9])

In [86]:
a[..., 1]

array([1, 5, 9])

In [87]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [88]:
from collections import deque

dp = deque(range(10), maxlen=10)
dp

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [89]:
dp.rotate(3)

In [90]:
dp

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)

In [94]:
dp.rotate(-2)
dp

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [95]:
dp.append(-1)

In [96]:
dp

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, -1], maxlen=10)

In [98]:
dp.appendleft(0)

In [99]:
dp

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [100]:
dp.extend([11,22,33])

In [101]:
dp

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33], maxlen=10)

In [102]:
dp.extendleft(range(3))
dp

deque([2, 1, 0, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [103]:
dp.extendleft([0, 1, 2])

In [104]:
dp

deque([2, 1, 0, 2, 1, 0, 3, 4, 5, 6], maxlen=10)

In [106]:
dp.extend([0,1,2])

In [107]:
dp

deque([2, 1, 0, 3, 4, 5, 6, 0, 1, 2], maxlen=10)